### PR TITLE
Fix typo in README.md

### LINKED ISSUE #33: Fix links in README.md
**Describe the bug**
Invalid links in README.md. These links don't work on [GitHub Pages](https://hammadmajid.github.io/algorithms).

```markdown
[code_of_conduct_link]: ./CODE_OF_CONDUCT.md
[license_link]: ./LICENSE
[contributing_link]: ./CONTRIBUTIING.md
```
**To Reproduce**
1. Go to [GitHub Pages](https://hammadmajid.github.io/algorithms).
2. Scroll down to [meta] section.
3. Click on any of the first three.

**Expected behavior**
GitHub blob of each file

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
# Description

Fixes #33 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [style guidelines](https://google.github.io/styleguide/cppguide.html) of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] My Changes follows the [contributing guidlines](https://github.com/hammadmajid/greedy-algorithm/blob/master/CONTRIBUTING.md) for this repository

### CODE REVIEW

**Comment by hammadmajid** [comment]
Thank you for fixing the typo. But this doesn't fix the issue.

**Comment by MaximSmolskiy** [comment]
@hammadmajid I commented the issue - I tried to reproduce problem and for me these links worked well

**Comment by hammadmajid** [comment]
My bad, I thought the problem was completely different.

**Comment by hammadmajid** [comment]
Deployed🚀

**Pull request merged**
